routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Route::get('/', function () {
//     return view('pages.index');
// });
Route::get('/', function () {
    return view('adminlte.master');
});

Route::resource('pertanyaan', 'PertanyaanController');
Route::get('/{pertanyaan_id}/KomentarPertanyaan/create', 'KomentarPertanyaanController@create')->name('KomentarPertanyaan.create');
Route::post('/KomentarPertanyaan', 'KomentarPertanyaanController@store')->name('KomentarPertanyaan.store');
Route::get('/KomentarPertanyaan', 'KomentarJawabanController@index')->name('komentar.index');
Route::GET('/KomentarPertanyaan/{pertanyaan_id}/edit', 'KomentarPertanyaanController@edit')->name('KomentarPertanyaan.edit');
Route::put('/KomentarPertanyaan/{pertanyaan_id}', 'KomentarPertanyaanController@update')->name('KomentarPertanyaan.update');
Route::delete('/KomentarPertanyaan/{pertanyaan_id}', 'KomentarPertanyaanController@destroy')->name('KomentarPertanyaan.destroy');


Route::get('/like/pertanyaan/{id}', 'VotePertanyaanController@like')->name('like.jawaban');
Route::get('/dislike/pertanyaan/{id}', 'VotePertanyaanController@dislike')->name('dislike.jawaban');

Route::resource('profil', 'ProfilController');
Route::resource('jawaban', 'JawabanController');
Route::GET('/jawaban-terbaik/{pertanyaan_id}/{jawaban_id}', 'JawabanController@terbaik')->name('jawaban.terbaik');
Route::GET('/create-jawaban/{id}', 'JawabanController@create_jawaban')->name('create.jawaban');
Route::GET('/edit-jawaban/{id}/edit/{pertanyaan_id}', 'JawabanController@edit_jawaban')->name('edit.jawaban');
Route::DELETE('/destroy-jawaban/{id}/{pertanyaan_id}', 'JawabanController@destroy_jawaban')->name('destroy.jawaban');
Auth::routes();

// laravel file manager
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/{jawaban_id}/komentar/create', 'KomentarJawabanController@create')->name('komentar.create');
Route::post('/komentar', 'KomentarJawabanController@store')->name('komentar.store');
Route::get('/{jawaban_id}/komentar', 'KomentarJawabanController@index')->name('komentar.index');
Route::get('/{id}/komentar/edit', 'KomentarJawabanController@edit')->name('komentar.edit');
Route::put('/{id}/komentar', 'KomentarJawabanController@update')->name('komentar.update');
Route::delete('/{id}/komentar', 'KomentarJawabanController@destroy')->name('komentar.destroy');

Route::get('/like/jawaban/{id}', 'VoteJawabanController@like')->name('like.jawaban');
Route::get('/dislike/jawaban/{id}', 'VoteJawabanController@dislike')->name('dislike.jawaban');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/user/list', 'HomeController@userList')->name('user.list');
Route::get('/home/user/pertanyaan', 'HomeController@userPertanyaan')->name('user.pertanyaan');

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
      <a href=" /pertanyaan " class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href=" /pertanyaan " class="nav-link">Pertanyaan</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <ul class="navbar-nav ml-auto">
      @guest
      <li class="nav-item">
        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
      </li>
      @if (Route::has('register'))
      <li class="nav-item">
        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
      </li>
      @endif
      @else
      <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        {{ Auth::user()->name }} <span class="caret"></span>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ route('logout') }}"
            onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </div>
      </li>
      @endguest
    </ul>

  </nav>

resources/views/adminlte/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="{{ asset('adminlte/dist/img/AdminLTELogo.png') }}"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Laravel Final Project</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href=" {{ route('profil.create') }} " class="d-block">
                {{{ isset(Auth::user()->profil->nama) ? Auth::user()->profil->nama : 'klik untuk buat nama' }}}
            </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item">
        <a href="/pertanyaan" class="nav-link">
            <i class="nav-icon fas fa-th"></i>
            <p>
            Home
            </p>
        </a>
        <li class="nav-item has-treeview">
            <a href="{{ route('user.pertanyaan') }}" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                My Post
              </p>
        </a>
        <li class="nav-item">
        <a href="/profil" class="nav-link">
            <i class="nav-icon fas fa-table""></i>
            <p>
            User list
            </p>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ route('logout') }}"
        onclick="event.preventDefault();
                      document.getElementById('logout-form').submit();">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>{{ __('Logout') }}</p>
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        </li>
       </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>