routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Route::get('/', function () {
//     return view('pages.index');
// });
Route::get('/', function () {
    return view('adminlte.master');
});

Route::resource('pertanyaan', 'PertanyaanController');
Route::get('/{pertanyaan_id}/KomentarPertanyaan/create', 'KomentarPertanyaanController@create')->name('KomentarPertanyaan.create');
Route::post('/KomentarPertanyaan', 'KomentarPertanyaanController@store')->name('KomentarPertanyaan.store');
Route::get('/KomentarPertanyaan', 'KomentarJawabanController@index')->name('komentar.index');
Route::GET('/KomentarPertanyaan/{pertanyaan_id}/edit', 'KomentarPertanyaanController@edit')->name('KomentarPertanyaan.edit');
Route::put('/KomentarPertanyaan/{pertanyaan_id}', 'KomentarPertanyaanController@update')->name('KomentarPertanyaan.update');
Route::delete('/KomentarPertanyaan/{pertanyaan_id}', 'KomentarPertanyaanController@destroy')->name('KomentarPertanyaan.destroy');


Route::get('/like/pertanyaan/{id}', 'VotePertanyaanController@like')->name('like.jawaban');
Route::get('/dislike/pertanyaan/{id}', 'VotePertanyaanController@dislike')->name('dislike.jawaban');

Route::resource('profil', 'ProfilController');
Route::resource('jawaban', 'JawabanController');
Route::GET('/jawaban-terbaik/{pertanyaan_id}/{jawaban_id}', 'JawabanController@terbaik')->name('jawaban.terbaik');
Route::GET('/create-jawaban/{id}', 'JawabanController@create_jawaban')->name('create.jawaban');
Route::GET('/edit-jawaban/{id}/edit/{pertanyaan_id}', 'JawabanController@edit_jawaban')->name('edit.jawaban');
Route::DELETE('/destroy-jawaban/{id}/{pertanyaan_id}', 'JawabanController@destroy_jawaban')->name('destroy.jawaban');
Auth::routes();

// laravel file manager
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/{jawaban_id}/komentar/create', 'KomentarJawabanController@create')->name('komentar.create');
Route::post('/komentar', 'KomentarJawabanController@store')->name('komentar.store');
Route::get('/{jawaban_id}/komentar', 'KomentarJawabanController@index')->name('komentar.index');
Route::get('/{id}/komentar/edit', 'KomentarJawabanController@edit')->name('komentar.edit');
Route::put('/{id}/komentar', 'KomentarJawabanController@update')->name('komentar.update');
Route::delete('/{id}/komentar', 'KomentarJawabanController@destroy')->name('komentar.destroy');

Route::get('/like/jawaban/{id}', 'VoteJawabanController@like')->name('like.jawaban');
Route::get('/dislike/jawaban/{id}', 'VoteJawabanController@dislike')->name('dislike.jawaban');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/user/list', 'HomeController@userList')->name('user.list');
Route::get('/home/user/pertanyaan', 'HomeController@userPertanyaan')->name('user.pertanyaan');

resources/views/pages/answer.blade.php
@extends('adminlte.master')

{{-- laravel file manager --}}
@include('scripts.lfm-head')

@section('content')
<form role="form" action=" {{ route('jawaban.store') }} " method="POST">
  @csrf
    <div class="card-body">
      <h3>Beri Jawaban</h3>
      <div class="form-group">
        <label for="isi">Isi</label>
        <input type="hidden" name="pertanyaan_id" value="{{$data->id}}">
        <textarea name="isi" class="form-control my-editor" placeholder="Masukan isi">{!! old('isi', '') !!}</textarea>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
@endsection

@include('scripts.lfm-bot')

resources/views/pages/answer_edit.blade.php
@extends('adminlte.master');

{{-- laravel file manager --}}
@include('scripts.lfm-head')

@section('content')
<form role="form" action=" {{ route('jawaban.update', ['jawaban' => $jawaban->id]) }} " method="POST">
  @csrf
  @method('PUT')
    <div class="card-body">
      <h3>Edit Jawaban</h3>
      <div class="form-group">
        <label for="isi">Isi</label>
        <input type="hidden" name="pertanyaan_id" value=" {{ $pertanyaan->id }} ">
        <textarea name="isi" class="form-control my-editor" placeholder="Masukan isi">{!! old('isi', $jawaban->isi ) !!}</textarea>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Edit</button>
    </div>
  </form>
@endsection

{{-- laravel file manager --}}
@include('scripts.lfm-bot')

resources/views/pages/create.blade.php
@extends('adminlte.master');

{{-- laravel file manager --}}
@include('scripts.lfm-head')

@section('content')
<form role="form" action=" {{ route('pertanyaan.store') }} " method="POST">
  @csrf
    <div class="card-body">
      <h3>Post a question</h3>
      <div class="form-group">
        <label for="judul">Judul</label>
        <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', '') }}" placeholder="Masukan judul">
      </div>
      <div class="form-group">
        <label for="isi">Isi</label>
        <textarea name="isi" class="form-control my-editor">{!! old('isi', '') !!}</textarea>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
@endsection

{{-- laravel file manager --}}
@include('scripts.lfm-bot')

@push('scripts')
  <script>
      Swal.fire({
          title: 'Berhasil!',
          text: 'Memasangkan script sweet alert',
          icon: 'success',
          confirmButtonText: 'Cool'
      })
  </script>
@endpush

resources/views/pages/data-tables.blade.php
@extends('adminlte.master')

@section('content')
<h1 class="mt-4 mb-4">Profil DataTable</h2>
    <table id="data-tables" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>email</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($posts as $post)
            <tr>
                    <td>{{ $post->nama }}</td>
                    <td>{{ $post->user->email }}</td>
                </tr>
            @endforeach
    </table>

@endsection

resources/views/pages/edit.blade.php
@extends('adminlte.master');

{{-- laravel file manager --}}
@include('scripts.lfm-head');

@section('content')
<form role="form" action=" {{ route('pertanyaan.update', ['pertanyaan' => $post->id]) }} " method="POST">
  @csrf
  @method('PUT')
    <div class="card-body">
      <h3>Edit question {{ $post->id }} </h3>
      <div class="form-group">
        <label for="judul">judul</label>
        <input type="text" class="form-control" id="judul" name="judul" value="{{ old('title', $post->judul) }}" placeholder="Masukan judul">
      </div>
      <div class="form-group">
        <label for="isi">isi</label>
        <textarea name="isi" class="form-control my-editor" placeholder="Insert isi">{!! old('isi', $post->isi) !!}</textarea>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Edit</button>
    </div>
  </form>
@endsection

{{-- laravel file manager --}}
@include('scripts.lfm-bot');

resources/views/pages/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 mx-3">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Daftar Pertanyaan</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
              <a href=" {{ route('pertanyaan.create') }} " class="btn btn-primary mb-2">Buat pertanyaan baru</a>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th style="width: 10px">#</th>
                <th>Pertanyaan</th>
                <th style="width: 40px">Actions</th>
              </tr>
            </thead>
            <tbody>
                @forelse ($posts as $key => $post)
                <tr>
                    <td> {{ $key + 1 }}</td>
                    <td> {{ $post->judul }} </td>
                    <td  style="display: flex;">
                        <a href="{{ route('pertanyaan.show', ['pertanyaan' => $post->id]) }}" class="btn btn-info btn-sm mr-1">show</a>

                        @if (Auth::user()->id == $post->user_id)
                            <a href="{{ route('pertanyaan.edit', ['pertanyaan' => $post->id]) }}" class="btn btn-warning btn-sm mr-1">edit</a>
                            <form action=" {{ route('pertanyaan.destroy', ['pertanyaan' => $post->id]) }} " method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" class="btn btn-danger btn-sm" value="delete">
                            </form>
                        @endif

                    </td>
                  </tr>
                @empty
                  <tr>
                      <td colspan="4" align="center"> No Data </td>
                  </tr>
                @endforelse
            </tbody>
          </table>
        </div>
      </div>
</div>
@endsection

resources/views/pages/profil_create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Buat Profil</title>
      <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
</head>
<body>
    <form role="form" action=" {{ route('profil.store') }} " method="POST">
        @csrf
          <div class="card-body">
            <h3>Masukan nama</h3>
            <div class="form-group">
              <label for="nama">Nama Lengkap</label>
              <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama', '') }}" placeholder="Masukan nama lengkap">
            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
</body>
</html>

resources/views/pages/show.blade.php
@extends('adminlte.master')

@php
    use App\VoteJawaban;
@endphp

@php
    use App\VotePertanyaan;
@endphp

@section('content')
    <div class="mt-3 mx-3">
    @if (session('success'))
        <div class="alert alert-success m-1">
            {{ session('success') }}
        </div>
    @endif
    <div class="card">
        <div class="card-header">
          <h1 class="card-title" style="font-size: 20px; font-weight:bold;">{{ $post->judul }}</h1>
        </div>
        <div class="card-body">
            {!! $post->isi !!}
        </div>
        <hr>
        <div class="mx-3">
            <p style="font-size: 12px">ditanyakan oleh : {{ isset($post->user->profil->nama) ? $post->user->profil->nama : 'anonim' }} </p>
            <p style="font-size: 12px">ditanyakan pada : {{ $post->created_at }} </p>
        </div>
        <tr>
            {{-- tombol jawab dan komentar --}}
    <table class="mx-3 mb-2">
        <tbody>
            <td  style="display: flex;">

                @if (Auth::user()->id != $post->user_id)
                    <a href="{{ route('create.jawaban',$post->id ) }}" class="btn btn-info btn-sm mr-1" style="width: 120px; font-size:12px;">Jawab Pertanyaan</a>
                    <a href="{{ route('KomentarPertanyaan.create',$post->id) }}" class="btn btn-warning btn-sm mr-1" style="width: 120px; font-size:12px;">Beri Komentar</a>
                @endif

                @if (Auth::user()->id == $post->user_id)
                    <a href="{{ route('pertanyaan.edit', ['pertanyaan' => $post->id]) }}" class="btn btn-info btn-sm mr-1">edit</a>
                    <form action=" {{ route('pertanyaan.destroy', ['pertanyaan' => $post->id]) }} " method="POST">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger btn-sm" value="delete">
                    </form>
                @endif
            </td>
        </tbody>
    </table>
        </tr>
      </div>
    </div>

    @foreach($post->Komentar as $jawaban)
    <div class="card mx-3">
        <div class="card-body">
            {{$jawaban->isi}}
        </div>
        <hr>
        <div class="mx-3 row">
            <div class="col-6">
                <p style="font-size: 12px">diberi komentar pada : {{ $jawaban->created_at }} </p>
            </div>
        </div>
        <table class="mx-3 mb-2">
            <tbody>
                <td style="display: flex;">
                    <a href="{{ route('KomentarPertanyaan.edit', ['pertanyaan_id' => $jawaban->id]) }}" class="btn btn-info btn-sm mr-1"  style="width: 60px; font-size:12px;">edit</a>
                    <form action=" {{ route('KomentarPertanyaan.destroy', ['pertanyaan_id' => $jawaban->id]) }} " method="POST" class="mr-2">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger btn-sm" value="delete">
                    </form>
                </td>
            </tbody>
        </table>
    </div>
    <br>
    @endforeach

    @foreach($post->jawaban as $jawaban)
    <div class="card mx-3">
        <div class="card-body">

            @if ($post->jawaban_tepat_id == $jawaban->id)
                <p style="background-color: green; font-size: 12px; color: white; width: 205px; border-radius: 5px; padding:5px;">Jawaban terbaik, dipilih oleh penanya</p>
            @endif


            {!! $jawaban->isi !!}
        </div>
        <hr>
        <div class="ml-3">
            <p style="font-size: 12px">dijawab oleh : {{ isset($jawaban->user->profil->nama) ? $jawaban->user->profil->nama : 'anonim' }} </p>
            <p style="font-size: 12px">dijawab pada : {{ $jawaban->created_at }} </p>
        <div class="mx-3 row">
            <div class="col-6">

            </div>
            <div class="col-6 text-right">
                <a href="{{ route('like.jawaban', ['id' => $jawaban->id]) }}">Like</a>
                @php
                    $votes = VoteJawaban::where('jawaban_id', $jawaban->id)->get();
                    $poin_arr = [];
                    foreach($votes as $vote) {
                        $poin_arr[] = $vote->poin;
                    }
                    $total_poin = array_sum($poin_arr);
                @endphp
                <span class="mx-1 text-bold">| Poin: {{ $total_poin }} |</span>
                <a href="{{ route('dislike.jawaban', ['id' => $jawaban->id]) }}">Dislike</a>
            </div>
        </div>
    <table class="mx-3 mb-2">
        <tbody>
            <td style="display: flex;">
                @if (Auth::user()->id == $post->user_id)
                <a href="{{ route('jawaban.terbaik', ['pertanyaan_id' => $post->id ,'jawaban_id' => $jawaban->id]) }}" class="btn btn-success btn-sm mx-1" style="width: 120px; font-size:12px;">Jawaban Terbaik</a>
                @endif

                @if (Auth::user()->id != $jawaban->user_id)
                    <a href="{{ route('komentar.create', ['jawaban_id' => $jawaban->id]) }}" class="btn btn-warning btn-sm mx-1" style="width: 120px; font-size:12px;">Beri Komentar</a>
                @endif

                @if (Auth::user()->id == $jawaban->user_id)
                    <a href="{{ route('edit.jawaban', ['id'=>$jawaban->id, 'pertanyaan_id'=>$post->id]) }}" class="btn btn-info btn-sm mr-1"  style="width: 60px; font-size:12px;">edit</a>
                    <form action=" {{ route('destroy.jawaban', ['id' => $jawaban->id, 'pertanyaan_id'=>$post->id]) }} " method="POST">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger btn-sm" value="delete">
                    </form>
                @endif
                <a href="{{ route('komentar.index', ['jawaban_id' => $jawaban->id]) }}">Lihat Komentar</a>
            </td>
        </tbody>
    </table>
    </div>
</div>
    <br>
    @endforeach

@endsection

@push('script')
    <script>
        Swal.fire({
            title: 'Berhasil!',
            text: 'Memasangkan script sweet alert',
            icon: 'success',
            confirmButtonText: 'Cool'
        })
    </script>
@endpush